# Default vm configuration
# virshle create <vm_definition.toml>
[domain]
"@type" = "kvm"
name = "vm-nixos"
uuid = "4dea24b3-1d52-d8f3-2516-782e98a23fa0"

# Ressources
vcpu = 2
[domain.memory]
"@unit" = "GiB"
"#text" = 4

[domain.clock]
"@sync" = "localtime"

[domain.devices]
emulator = "/run/libvirt/nix-emulators/qemu-kvm"

#################################
## SMBIOS

# [domain.os.type]
# "#text" = "hvm"
# "@type" = "x86_64"
#
# [domain.os.bios]
# "@useserial" = "yes"
# "@rebootTimeout" = "10"
#
# [domain.os.bootmenu]
# "@enable" = "yes"
# "@timeout" = "3000"
#

#################################
## EFI

# [domain.os]
# "@firmware" = 'efi'

[domain.os.boot]
"@dev" = "hd"

[domain.os.type]
"@arch" = "x86_64"
"@machine" = "pc-q35-3.0"
"#text" = "hvm"

[domain.os.nvram]
"#text" = "./iso/OVMF_VARS.fd"
"@readonly" = "yes"

[domain.os.loader]
"@secure" = "no"
"@readonly" = "yes"
"@type" = "pflash"
"#text" = "/run/libvirt/nix-ovmf/OVMF_CODE.fd"

[domain.features.acpi]
[domain.features.apic]

[domain.features.smm]
"@state" = "on"

# [domain.os.smbios]
# "@mode" = "sysinfo"

# [domain.os.bios]
# "@useserial" = "yes"
# "@rebootTimeout" = "10"

# [domain.os.bootmenu]
# "@enable" = "yes"
# "@timeout" = "3000"

#################################
## EFI with bad nixos compat

# [[domain.os.firmware.feature]]
# "@enabled" = "no"
# "@name" = "secure-boot"
#
# [[domain.os.firmware.feature]]
# "@enabled" = "no"
# "@name" = "enrolled-keys"

#################################
# OS - Cdrom

# [[domain.devices.disk]]
# "@type" = "file"
# "@device" = "cdrom"
# source."@file" = "./iso/nixos.iso"
# [domain.devices.disk.target]
# "@dev" = "hdc"
# "@bus" = "ide"

#################################
# OS

[[domain.devices.disk]]
"@type" = "file"
"@device" = "disk"
[domain.devices.disk.source]
"@file" = "./iso/nixos.qcow2"
[domain.devices.disk.driver]
"@name" = "qemu"
"@type" = "qcow2"
[domain.devices.disk.target]
"@dev" = "vda"
"@bus" = "virtio"
[domain.devices.disk.alias]
"@name" = "nixos"

#################################
# Pipelight-init

# [[domain.devices.disk]]
# "@type" = "file"
# "@device" = "disk"
# source."@file" = "./iso/pipelight-init.img"
# Bug: Target is gnored by libvirt
# Fix: Use serial instead and retrieve at path:
# /dev/disk/by-id/<bus>-<serial>
# serial = "pipelight-init"
# [domain.devices.disk.target]
# "@dev" = "vdd"
# "@bus" = "virtio"


#################################
# Configuration storage

# [[domain.devices.disk]]
# "@type" = "file"
# "@device" = "disk"
# source."@file" = "~/.libvirt/volumes/standard/20M.img"
# [domain.devices.disk.target]
# "@dev" = "hdb"
# "@bus" = "virtio"

#################################
# Storage

# [[domain.devices.disk]]
#
# "@type" = "file"
# "@device" = "disk"
# source."@file" = "~/.libvirt/volumes/standard/10G.img"
#
# [domain.devices.disk.target]
# "@dev" = "hda"
# "@bus" = "virtio"
#
#################################
# Network

[[domain.devices.interface]]
"@type" = "network"
source."@network" = "default_6"
model."@type" = "virtio"

#################################
# Utils
## Redirect guest output to host

# [[domain.devices.console]]
# "@type" = "pty"
# [domain.devices.console.target]
# "@type" = "serial"
# "@port" = "0"


#################################
# Utils
## Redirect guest output to host

[domain.devices.serial]
"@type" = "pty"
source."@path" = "/dev/pts/0"
alias."@name" = 'serial0'

[domain.devices.serial.target]
"@type" = "isa-serial"
model."@name" = "isa-serial"
"@port" = 0

[domain.devices.console]
"@type" = "pty"
"@tty" = "/dev/pts/0"
source."@path" = "/dev/pts/0"
alias."@name" = "serial0"

[domain.devices.console.target]
"@type" = "serial"
"@port" = 0
