# Utils - Some cool stuffs to put in your VM definition

#################################
## Redirect guest output
## to the host terminal.

[domain.devices.serial]
"@type" = "pty"
source."@path" = "/dev/pts/0"
alias."@name" = 'serial0'

[domain.devices.serial.target]
"@type" = "isa-serial"
model."@name" = "isa-serial"
"@port" = 0

[domain.devices.console]
"@type" = "pty"
"@tty" = "/dev/pts/0"
source."@path" = "/dev/pts/0"
alias."@name" = "serial0"

[domain.devices.console.target]
"@type" = "serial"
"@port" = 0

#################################
## Set a boot delay

[domain.os.bios]
"@useserial" = "yes"
"@rebootTimeout" = "10"

[domain.os.bootmenu]
"@enable" = "yes"
"@timeout" = "3000"

#################################
## Provision
# with Pipelight-init

[[domain.devices.disk]]
# Bug: Target is ignored by libvirt
# Fix: Use serial instead and retrieve at path:
# /dev/disk/by-id/<bus>-<serial>
"@type" = "file"
"@device" = "disk"
source."@file" = "./iso/pipelight-init.img"
serial = "pipelight-init"
[domain.devices.disk.target]
"@dev" = "vdd"
"@bus" = "virtio"
