name = "default_xs"
uuid = "b30458d1-7c7f-4d06-acc2-159e43892e87"
vcpu = 1
vram = 2

[[disk]]
name = "os"
# fullpath with xwr permissions on image
path = "/home/anon/Iso/nixos.img"
size = "50G"

[[disk]]
name = "init"
# fullpath with xwr permissions on image
path = "/home/anon/Iso/pipelight-init.img"
size = "10M"

[[net]]
[net.tap]
