[[pipelines]]
name = "tests"

[[pipelines.steps]]
name = "deno internal tests"
commands = [
  "deno run -A ./mod.ts ",
  "deno run -A ./mod.ts define ./examples/machine.toml -vvv",
]

[[pipelines.steps]]
name = "virsh integration tests"
commands = ["deno test"]
