[[pipelines]]
name = "tests"

[[pipelines.steps]]
name = "display help"
commands = [
  "deno run -A ./mod.ts ",
]

[[pipelines.steps]]
name = "clean c"
commands = ["deno run -A ./mod.ts define ./base/domain/default.toml -vvv"]

[[pipelines.steps]]
name = "virsh integration tests"
commands = ["deno test"]
