[[connect]]
name = "default"
url = "file:///var/lib/virshle/virshle.sock"

[[connect]]
name = "default-ssh"
url = "ssh://anon@localhost:22/var/lib/virshle/virshle.sock"

[[template]]

# Vms
# Standard sizes with decents presets.

[template.vm]
name = "xs"
vcpu = 1
vram = 2
[[template.vm.disk]]
size = "50G"

[template.vm]
name = "s"
vcpu = 2
vram = 4
[[template.vm.disk]]
size = "80G"

[template.vm]
name = "m"
vcpu = 4
vram = 8
size = "100G"

[template.vm]
name = "l"
vcpu = 6
vram = 10
size = "150G"

[template.vm]
name = "xl"
vcpu = 8
vram = 16
size = "180G"

# Default network ipv6 and ipv4 only
[template.net]
name = "default_6"
# subnet = "192.168.200.1/24"

# Default network ipv4 only
[template.net]
name = "default"
subnet = "192.168.200.1/24"
