//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.12

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "account")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique)]
    pub uuid: Uuid,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::account_vm::Entity")]
    AccountVm,
}

impl Related<super::account_vm::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AccountVm.def()
    }
}

impl Related<super::vm::Entity> for Entity {
    fn to() -> RelationDef {
        super::account_vm::Relation::Vm.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::account_vm::Relation::Account.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
