//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.12

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "lease")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub vm_id: i32,
    #[sea_orm(unique)]
    pub ip: String,
    pub created_at: DateTime,
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::vm::Entity",
        from = "Column::VmId",
        to = "super::vm::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Vm,
}

impl Related<super::vm::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Vm.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
