# Secret definition
[[secret]]
"@ephemeral" = "no"
"@private" = "yes"

[secret.value]
"#text" = "abc123"

[secret.description]
"#text" = "Luks storage secret"
[secret.uuid]
"#text" = "d6e7d1f8-1cca-4fb3-b985-7ca74cf7cbb9"
