use crate::config::UserData;
use crate::hypervisor::{
    disk::{Disk, InitDisk},
    Vm,
};
use crate::network::utils::{uuid_to_duid, uuid_to_mac};

use unindent::unindent;

pub use uuid::Uuid;

// Templating engine

// Mac
use serde::{Deserialize, Serialize};
use std::net::IpAddr;

// "mkdir -p ./scripts/mnt/pipelight-init",
// "mount -t ext4 -o loop ./scripts/pipelight-init.img ./scripts/mnt/pipelight-init",
// "cp -r /pipelight-init/.* ./scripts/mnt/pipelight-init",
// "cp -r /pipelight-init/* ./scripts/mnt/pipelight-init",
// "umount ./scripts/mnt/pipelight-init",

// Error handling
use miette::Result;
use tracing::{debug, info};
use virshle_error::VirshleError;

#[derive(Default, Debug, Serialize, Deserialize, Clone, Eq, PartialEq)]
pub struct InitData {
    // Autogenerated data.
    pub vm_data: Option<VmData>,
    // User defined data.
    pub user_data: Option<UserData>,
}

/// Autogenerated data:
/// - mac or mac_address is based on VM uuid.
/// - dhcp duid-uuid is based on VM uuid.
/// - hostname is the VM name generated on VM creation.
#[derive(Debug, Serialize, Deserialize, Clone, Eq, PartialEq)]
pub struct VmData {
    mac: String,
    duid: String,
    hostname: String,
}

impl Into<VmData> for Vm {
    fn into(self) -> VmData {
        (&self).into()
    }
}
impl Into<VmData> for &Vm {
    fn into(self) -> VmData {
        VmData {
            mac: uuid_to_mac(&self.uuid).to_string(),
            duid: uuid_to_duid(&self.uuid),
            hostname: self.name.to_owned(),
        }
    }
}

impl InitData {
    /// Convert user-data into a pipelight configuration file.
    pub fn to_pipelight_toml_config(&self) -> Result<String, VirshleError> {
        // Run before network is up
        let mut p_config = "".to_owned();

        p_config += &unindent(&format!(
            r#"
        [[pipelines]]
        name = "init_net_pre"
        "#
        ))
        .to_owned();

        if let Some(vm_data) = &self.vm_data {
            // Add hostname
            let hostname = vm_data.hostname.clone();
            p_config += &unindent(&format!(
                r#"
            [[pipelines.steps]]
            name = "set hostname"
            commands = [
                "sysctl -w kernel.hostname='{hostname}'",
            ]
            "#
            ));
            // Set dhcp persistent identifier (duid-uuid).
            // So the Vm can obtain the same ip from dhcp accross hardware (disk) changes.
            let duid = vm_data.duid.clone();
            p_config += &unindent(&format!(
                r#"
            [[pipelines.steps]]
            name = "set dhcp persistent identifier"
            commands = [
                "mkdir -p /var/lib/dhcpcd",
                "touch /var/lib/dhcpcd/duid",
                "echo \"{duid}\n\" > /var/lib/dhcpcd/duid",
                "chown -R dhcpcd:dhcpcd /var/lib/dhcpcd"
            ]
            "#,
            ));
        }
        if let Some(user_data) = &self.user_data {
            //
            for user in &user_data.user {
                if let Some(ssh) = &user.ssh {
                    let username = user.name.clone();
                    let keys = ssh.authorized_keys.to_owned();
                    let mut commands = vec![];

                    p_config += &unindent(&format!(
                        r#"
                    [[pipelines.steps]]
                    name = "ensure user {username} exists"
                    options.mode = "jump_next"
                    commands = [
                        "useradd -m {username} -G wheel"
                    ]
                    "#
                    ));

                    // Add keys
                    for key in keys {
                        commands.push(unindent(&format!(
                            r#""echo \"{key}\n\" >> /etc/ssh/authorized_keys.d/{username}","#
                        )));
                    }
                    let commands = commands.join(",\n");

                    p_config += &unindent(&format!(
                        r#"
                    [[pipelines.steps]]
                    name = "set authorized ssh keys for user {username}"
                    options.mode = "jump_next"
                    commands = [
                        "mkdir -p /etc/ssh/authorized_keys.d",
                        "touch /etc/ssh/authorized_keys.d/{username}",
                        {commands}
                    ]
                    "#
                    ));
                }
            }
        }
        // Run after network is up
        p_config += &unindent(&format!(
            r#"
        [[pipelines]]
        name = "init_net_post"
        "#
        ));
        p_config += &unindent(&format!(
            r#"
            [[pipelines.steps]]
            name = "set main network interface kernel configuration"
            commands = [
                "sysctl -w net.ipv6.conf.ens4.accept_ra=1"
            ]
            "#
        ));

        Ok(p_config)
    }
}

impl Vm {
    /// Create and provision an init disk,
    /// and add it vm config.
    #[tracing::instrument]
    pub fn add_init_disk(&mut self, user_data: Option<UserData>) -> Result<&Self, VirshleError> {
        debug!("Creating an init disk for vm {}", self.uuid);

        // Make disk
        let init_disk = InitDisk { vm: &*self };
        let init_data = InitData {
            vm_data: Some((&*self).into()),
            user_data,
        };
        init_disk
            .create()?
            .mount()?
            .write_init_files(&init_data)?
            .umount()?;

        // Add to vm config
        let disk = Disk::from(&init_disk);
        self.disk.push(disk);

        Ok(self)
    }
}

#[cfg(test)]
mod test {
    use super::*;
    use crate::config::{SshParams, User};

    #[test]
    fn test_pipelight_config_render() -> Result<()> {
        let uuid = &Uuid::new_v4();
        let init_data = InitData {
            vm_data: Some(VmData {
                mac: uuid_to_mac(&uuid).to_string().to_owned(),
                duid: uuid_to_duid(&uuid),
                hostname: "izuku_midoryia".to_owned(),
            }),
            user_data: Some(UserData {
                user: vec![User {
                    name: "anon".to_owned(),
                    ssh: Some(SshParams {
                        authorized_keys: vec!["ssh-ed25519 AAAAD3N".to_owned()],
                    }),
                }],
                ..Default::default()
            }),
        };
        let res = init_data.to_pipelight_toml_config()?;
        println!("{}", res);
        Ok(())
    }
    // #[tokio::test]
    async fn test_init_disk_creation() -> Result<()> {
        // let vm = Vm::default();
        let vms = Vm::database().await?.many().get().await?;
        let mut vm = vms.first().unwrap().to_owned();
        // println!("{:#?}", &vm);

        vm.add_init_disk(None)?;
        Ok(())
    }
}
