# The simplest Nixos Vm (default):
# - storage: a single qcow2 image.
# - network: minimal config
# - boot: ultra fast boot time (efi+systemd-boot).
# - connect with "virsh console vm-nixos".

#################################
## VM

[domain]
"@type" = "kvm"
name = "vm-nixos"
uuid = "4dea24b3-1d52-d8f3-2516-782e98a23fa0"

# Resources
vcpu = 2
[domain.memory]
"@unit" = "GiB"
"#text" = 4

[domain.clock]
"@sync" = "localtime"

[domain.devices]
emulator = "/run/libvirt/nix-emulators/qemu-kvm"

#################################
## EFI

[domain.os.boot]
"@dev" = "hd"

[domain.os.type]
"@arch" = "x86_64"
"@machine" = "pc-q35-3.0"
"#text" = "hvm"

[domain.os.nvram]
"#text" = "~/Iso/OVMF_VARS.fd"
"@readonly" = "yes"

[domain.os.loader]
"@secure" = "no"
"@readonly" = "yes"
"@type" = "pflash"
"#text" = "/run/libvirt/nix-ovmf/OVMF_CODE.fd"

[domain.features.acpi]
[domain.features.apic]

[domain.features.smm]
"@state" = "on"

#################################
## Storage
# Os

# Secret definition
[[secret]]
"@ephemeral" = "no"
"@private" = "yes"
[secret.value]
"#text" = "abc123"
[secret.description]
"#text" = "Luks storage secret"
[secret.uuid]
"#text" = "d6e7d1f8-1cca-4fb3-b985-7ca74cf7cbb9"

# Encrypted device
[[domain.devices.disk]]
"@type" = "file"
"@device" = "disk"
[domain.devices.disk.source]
"@file" = "~/Iso/encrypted.qcow2"
[domain.devices.disk.driver]
"@name" = "qemu"
"@type" = "qcow2"
[domain.devices.disk.target]
"@dev" = "vda"
"@bus" = "virtio"
[domain.devices.disk.alias]
"@name" = "encrypted"
# Luks settings
[domain.devices.disk.encryption]
"@format" = "luks"
[domain.devices.disk.encryption.secret]
"@type" = "passphrase"
"@uuid" = "d6e7d1f8-1cca-4fb3-b985-7ca74cf7cbb9"


#################################
## Network

[[domain.devices.interface]]
"@type" = "network"
source."@network" = "default_6"
model."@type" = "virtio"

#################################
## Utils
# Redirect guest output to host

[domain.devices.serial]
"@type" = "pty"
source."@path" = "/dev/pts/0"
alias."@name" = 'serial0'

[domain.devices.serial.target]
"@type" = "isa-serial"
model."@name" = "isa-serial"
"@port" = 0

[domain.devices.console]
"@type" = "pty"
"@tty" = "/dev/pts/0"
source."@path" = "/dev/pts/0"
alias."@name" = "serial0"

[domain.devices.console.target]
"@type" = "serial"
"@port" = 0
