//!
//! Database connection and struct mapping.
//!

mod connect;

// The entity directocy is autogenerated with sea-orm.
pub mod entity;
pub use entity::*;

// Reexports
// pub use crud::*;
pub use connect::{connect_db, fresh_db};
