[package]
name = "virshle_core"
version = "0.1.1"
edition = "2021"

[dependencies]
virshle_error = { path = "../virshle_error" }

miette = { version = "7.2.0", features = ["fancy"] }
pipelight_error = { version = "0.2.9" }
quick-xml = { version = "0.36.2", features = ["serde", "serialize"] }
serde_json = { version = "1.0.128", features = ["preserve_order"] }
toml = "0.8.19"
log = "0.4.22"
virt = "0.4.1"
thiserror = "1.0.63"
serde = { version = "1.0.210", features = ["derive"] }
# tabled = { version = "0.16.0", features = ["ansi"] }
tabled = { version = "=0.15.0", features = ["ansi"] }
strum = { version = "0.26.3", features = ["derive"] }
convert_case = "0.6.0"
owo-colors = "4.1.0"
env_logger = "0.11.5"
uuid = { version = "1.10.0", features = ["serde", "v4"] }
bat = "0.24.0"
crossterm = "0.28.1"
shellexpand = "3.1.0"
once_cell = "1.19.0"
human_bytes = "0.4.3"
names = "0.14.0"
rand = "0.8.5"
minidom = "0.16.0"
regex = "1.10.6"
bon = "2.3.0"
pipelight_exec = "0.2.8"
reqwest = "0.12.7"
tokio = { version = "1.40.0", features = ["full"] }
hyper-socket = "0.2.0"
hyper = { version = "1.4.1", features = ["full"] }
http-body-util = "0.1.2"
hyper-util = "0.1.9"
hyperlocal = "0.9.1"
ureq = "2.10.1"
config = "0.14.0"

vmm = { git = "https://github.com/cloud-hypervisor/cloud-hypervisor", features = [
  "kvm",
] }
sea-orm = { version = "1.0.1", features = [
  "runtime-tokio-rustls",
  "sqlx-sqlite",
  "with-json",
  "macros",
] }
migration = { path = "../migration" }
russh = "0.45.0"
url = "2.5.2"
async-trait = "0.1.83"
axum = "0.7.7"
tower = "0.5.1"
clap-verbosity-flag = "2.2.2"
clap = "4.5.20"
clap_complete = "4.5.33"
