#######################
# Crocuda account user-data
[account]
uuid = "6cff9c9c-8713-40ca-b950-669bae24d9c9"
[account.user]
name = "anon"
public_key = "ssh-ed25519 AAAAC3N"


#######################
# Conventional user-data
[ssh]
[[ssh.user]]
name = "anon"
authorized_keys = ["ssh-ed25519 AAAAC3N"]
