#######################
# Conventional user-data

# Will be dispatched in the VM at /etc/ssh/authorized_keys.d/
[[user]]
name = "anon"
[user.ssh]
authorized_keys = ["ssh-ed25519 AAAAC3N"]

#######################
# Crocuda account user-data

# Remains is the VM definition inside the database
[account]
uuid = "6cff9c9c-8713-40ca-b950-669bae24d9c9"
