#########################
# Nodes

# Instance (This host credentials)
[[node]]
name = "local"
url = "unix:///var/lib/virshle/virshle.sock"
weight = 20

[[node]]
name = "local-ssh"
url = "ssh://anon@deku:22/var/lib/virshle/virshle.sock"
weight = 0

[[node]]
name = "rpi4b"
url = "ssh://anon@rpi4b:22/var/lib/virshle/virshle.sock"
weight = 10


#########################
# Testing Templates: 
# for testing vm
[[template.vm]]
name = "xs-offline"
vcpu = 1
vram = 2
[[template.vm.disk]]
name = "os"
path = "~/Iso/nixos.xxs.efi.img"

[[template.vm]]
name = "xs-tap"
vcpu = 1
vram = 2
[[template.vm.disk]]
name = "os"
path = "~/Iso/nixos.xxs.efi.img"
[[template.vm.net]]
name = "main"
[template.vm.net.type.tap]

[[template.vm]]
name = "xs-macvtap"
vcpu = 1
vram = 2
[[template.vm.disk]]
name = "os"
path = "~/Iso/nixos.xxs.efi.img"
[[template.vm.net]]
name = "main"
[template.vm.net.type.mac_v_tap]

[[template.vm]]
name = "xs-dpdk"
vcpu = 1
vram = 2
[[template.vm.disk]]
name = "os"
path = "~/Iso/nixos.xxs.efi.img"
[[template.vm.net]]
name = "main"
[template.vm.net.type.vhost]

#########################

[[template.vm]]
name = "xxs"
vcpu = 1
vram = 2
[[template.vm.disk]]
name = "os"
path = "~/Iso/nixos.xxs.efi.img"
[[template.vm.net]]
name = "main"
[template.vm.net.type.tap]

#########################
# Templates: 
# vm standard sizes with decents presets.

[[template.vm]]
name = "xs"
vcpu = 1
vram = 2
[[template.vm.disk]]
name = "os"
path = "~/Iso/nixos.xs.efi.img"
[[template.vm.net]]
name = "main"
[template.vm.net.type.tap]

[[template.vm]]
name = "s"
vcpu = 2
vram = 4
[[template.vm.disk]]
name = "os"
path = "~/Iso/nixos.s.efi.img"
[[template.vm.net]]
name = "main"
[template.vm.net.type.tap]

[[template.vm]]
name = "m"
vcpu = 4
vram = 8
[[template.vm.disk]]
name = "os"
path = "~/Iso/nixos.m.efi.img"
[[template.vm.net]]
name = "main"
[template.vm.net.type.tap]

# Big vms (for beta release)

# [[template.vm]]
# name = "l"
# vcpu = 6
# vram = 10
# [[template.vm.disk]]
# name = "os"
# path = "~/Iso/nixos.efi.img"
# size = "150G"
#
# [[template.vm]]
# name = "xl"
# vcpu = 8
# vram = 16
# [[template.vm.disk]]
# name = "os"
# path = "~/Iso/nixos.efi.img"
# size = "180G"

#########################
# Network

## Kea dhcp
[dhcp]
[dhcp.kea]
url = "tcp://localhost:5547"

## Fake dhcp when no dhcp available on network
# [dhcp.fake.pool.main]
# subnet = "2a02:842b:6361:ad01::/64"
# range = ["2a02:842b:6361:ad01::1ff", "2a02:842b:6361:ad01::ffff"]
