[[connect]]
name = "default"
url = "file:///var/lib/virshle/virshle.sock"

[[connect]]
name = "default-ssh"
url = "ssh://anon@localhost:22/var/lib/virshle/virshle.sock"

[template]
# Vms
# Standard sizes with decents presets.
[[template.vm]]
name = "xs"
vcpu = 1
vram = 2
[[template.vm.disk]]
name = "os"
path = "~/Iso/nixos.efi.img"
size = "50G"
[[template.vm.net]]
name = "main"
[template.vm.net.type.vhost]

[[template.vm]]
name = "s"
vcpu = 2
vram = 4
[[template.vm.disk]]
name = "os"
path = "~/Iso/pipelight-init.img"
size = "80G"

[[template.vm]]
name = "m"
vcpu = 4
vram = 8
[[template.vm.disk]]
name = "os"
path = "~/Iso/nixos.efi.img"
size = "100G"

#########################
# Big vms

# [[template.vm]]
# name = "l"
# vcpu = 6
# vram = 10
# [[template.vm.disk]]
# name = "os"
# path = "~/Fast/nixos/vm/result/nixos.img"
# size = "150G"
#
# [[template.vm]]
# name = "xl"
# vcpu = 8
# vram = 16
# [[template.vm.disk]]
# name = "os"
# path = "~/Fast/nixos/vm/result/nixos.img"
# size = "180G"#

##########################
# Internal network for fast vm communication

# [[template.net]]
# name = "default"
# subnet = "192.168.200.1/24" #CIDR notation
