#########################
# This deamon/host configuration
[node]
# alias = "<location>-<branch>-<n>"
alias = "deku-dev-1"
# private_key = "/var/lib/virshle/node/id_ed25519"
# public_key = "/var/lib/virshle/node/id_ed25519.pub"
private_key = "./keys/default"
public_key = "./keys/default.pub"

# Mandatory
# Set your node to "passive=true" when:
# - you don't want to create local vms,
# - you want to connect to other nodes only.
passive = false

# Network
## Kea dhcp
[network.dhcp.kea]
url = "tcp://localhost:5547"
suffix = "vm"

## Fake dhcp when no dhcp available on network
# [dhcp.fake.pool.main]
# subnet = "2a02:842b:6361:ad01::/64"
# range = ["2a02:842b:6361:ad01::1ff", "2a02:842b:6361:ad01::ffff"]

#########################
# Peers
# The cli can communicate with remote nodes (peers).
# If none is whitelisted you will by default send commands to the local node (Self).

[[peer]]
url = "ssh://anon@home-v0:2214/var/lib/virshle/virshle.sock"
weight = 20
# Whitelist the node by adding its pubkey.
# public_key = "/var/lib/virshle/node/peers/id_ed25519.pub"

# [[peers]]
# alias = "local-ssh"
# url = "ssh://anon@deku:22/var/lib/virshle/virshle.sock"
# weight = 0
#
# [[peers]]
# alias = "rpi4b"
# url = "ssh://anon@rpi4b:22/var/lib/virshle/virshle.sock"
# weight = 10


#########################
# Testing Templates: 
# for testing vm

# No network
[[template.vm]]
name = "xxs-offline"
vcpu = 1
vram = "2GiB"
[[template.vm.disk]]
name = "os"
path = "~/Iso/nixos.xxs.efi.img"

# Tap network device
[[template.vm]]
name = "xxs-tap"
vcpu = 1
vram = "2GiB"
[[template.vm.disk]]
name = "os"
path = "~/Iso/nixos.xxs.efi.img"
[[template.vm.net]]
name = "main"
[template.vm.net.type.tap]

# Macvtap network device
# Not working yet as of Cloud-hypervisor 42.0 but still we get prepared.
[[template.vm]]
name = "xxs-macvtap"
vcpu = 1
vram = "2GiB"
[[template.vm.disk]]
name = "os"
path = "~/Iso/nixos.xxs.efi.img"
[[template.vm.net]]
name = "main"
[template.vm.net.type.macvtap]


#########################
# Templates: 
# vm standard sizes with decents presets.

[[template.vm]]
name = "xxs"
vcpu = 1
vram = "1GiB"
[[template.vm.disk]]
name = "os"
path = "~/Iso/nixos.xxs.efi.img"
[[template.vm.net]]
name = "main"
[template.vm.net.type.tap]

[[template.vm]]
name = "xs"
vcpu = 1
vram = "2GiB"
[[template.vm.disk]]
name = "os"
path = "~/Iso/nixos.xs.efi.img"
[[template.vm.net]]
name = "main"
[template.vm.net.type.tap]

[[template.vm]]
name = "s"
vcpu = 2
vram = "4GiB"
[[template.vm.disk]]
name = "os"
path = "~/Iso/nixos.s.efi.img"
[[template.vm.net]]
name = "main"
[template.vm.net.type.tap]

# Big vms (for beta release)

# [[template.vm]]
# name = "m"
# vcpu = 4
# vram = "8GiB"
# [[template.vm.disk]]
# name = "os"
# path = "~/Iso/nixos.m.efi.img"
# [[template.vm.net]]
# name = "main"
# [template.vm.net.type.tap]

# [[template.vm]]
# name = "l"
# vcpu = 6
# vram = "10GiB"
# [[template.vm.disk]]
# name = "os"
# path = "~/Iso/nixos.l.efi.img"
# [[template.vm.net]]
# name = "main"
# [template.vm.net.type.tap]

# [[template.vm]]
# name = "xl"
# vcpu = 8
# vram = "16GiB"
# [[template.vm.disk]]
# name = "os"
# path = "~/Iso/nixos.xl.efi.img"
# [[template.vm.net]]
# name = "main"
# [template.vm.net.type.tap]
